services:
  - type: web
    name: testeoak-backend
    env: node
    rootDirectory: backend
    buildCommand: cp .env.production .env && npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
    region: oregon
    numInstances: 1
    buildFilter:
      paths:
        - backend/**/*.ts
        - backend/**/*.json
        - backend/package.json
        - backend/package-lock.json
        - backend/.env.production
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" 